### ISSUE TITLE
As a citizen user, add logging to my integration

### ISSUE THREAD

**Issue by jimmidyson** [syndesisio/syndesis-project#1]
As a citizen user, I would like to add one or more steps to an integration flow that allow me to log context around the processing of the integration.  For example, after receiving a message from Twitter, I may want to record the received Tweet data in the log for evaluation later.

To begin with, I'd like access to three pieces of context for logging:
* The message body.  This is the data that's currently being processed in the integration flow and resolvable via ${body}. 
* One or more message headers.  Message headers are more technical in nature, but can be very relevant to processing in an integration.  It's likely that I've either read some documentation, been told by an expert user, or instructed by support to log specific headers vs. figuring out header names on my own.
* Free form content.  I may want to log static text each time an integration flow is triggered, e.g. "Citizen User in Action!".

I may want to do each of the above individually or together (e.g. print some static text along with a header value), so the logging interface should support both use cases.

I'm not an expert in logging syntax, so it would be very helpful if the iPaaS UI provided help with configuring a log step for the use cases above.  For example, providing example log statements that are 'clickable' and automatically populate the log configuration text area.

At this point in time, we assume that logs are viewed separately (through OpenShift console), although a future sprint will address viewing logs directly in the iPaaS UI.

Background info:
https://docs.google.com/document/d/15qq-mIf_EAV2bEgbg44zXDMTI-ev1QChGriiwlulRA0/edit

**Comment by rhuss** [comment]
Part of this epic also how to _view_ these logs:

- from where to access a log viewer
- how the log viewer should look like (e.g. like the OpenShift log viewer ?)
- filter on log messages only from the integration
- saving / download of logs ?

**Comment by sjcox-rh** [comment]
Im working on the designs for the log step and I had a of couple questions.

1. When selecting the log level (error, warning, info,debugging, tracing - in that order) I was under the impression that if you selected one, all levels listed prior to it would be auto selected as well. For example, if you selected info, warning and error would be logged as well. Is that still the case?

2. Would we want to offer an way to get to a custom/advanced editor from this step, which is essentially an html box for more advanced users within the log step? Or did we want to have a separate advanced log step, similar to how we separated out the filter and advanced filter step?

3. Log Viewer: After speaking with the UX team, we feel it would make the most sense to access the log for each integration within the integration details page.  Or is there a log viewer for the whole app that shows all integration logs?

4. @rhuss, above you mentioned "filter on log messages only from integration". Does this mean that every integration will have a log viewer that shows the whole log. But then you can filter on to show only logs messages from a log step the user added to the integration?

5. When you create a log step, does it apply to the whole integration (before and after the step) or does the location of the step within the integration affect what is logged?

Sorry for so many questions, just wanted to make sure I fully understood the feature!

@iocanel @kcbabo @jimmidyson @dongniwang @amysueg

**Comment by rhuss** [comment]
@sjcox-rh thanks for your comment. The issue has moved to https://github.com/syndesisio/syndesis/issues/173, could you please copy your comment there? These issues are going to be closed soon.

I will the answer it on the other issue ;-)

**Comment by sjcox-rh** [comment]
@rhuss Sure thing! ill do that now :]
