### ISSUE TITLE
Use reencrypt routes for effectively end-to-end TLS

### ISSUE THREAD

**Issue by jimmidyson** [syndesisio/syndesis-project#101]
Currently, connections are terminated on the OpenShift router and then plain from router to pods. With OpenShift >=3.6, we can now use reencrypt TLS routes with service serving certificates to effectively achieve end-to-end TLS. This requires changes in almost every Syndesis project, but should all be configuration rather than code changes.

**Comment by rhuss** [comment]
Should we wait until we have decided how to proceed with dev environment (which is still 3.5) ?
