### ISSUE TITLE
Please add a button to export integration into another environment

### ISSUE THREAD

**Issue by sjavurek** [syndesisio/syndesis-project#105]
We'd like to be able to export the FIS project to see the code and also import it into another iPaaS environment to facilitate reproducing issues.

**Comment by sjavurek** [comment]
This should also include an import button to pull in the exported project. I just wanted another button.  :-)

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (153/150 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:39195)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nmd-0013YY-Gn
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:16 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=R78lEscYSDdxKaM3E06IhojPytM=; b=lDGBApaoYKraxm6R
	7Djhy38a6deL+3cuPRHDi8i9OijiTOoiBCURi7PFB2xn3aFnFNklgG6vO/Bh0/Sl
	uOcqAtjHYKqbI8JJh2TVyEBxcRmD1rAEirb9DLk9vlij9nFviCe7p/mzyjKEZIuB
	6CZM4cYDdSNIEgI38V0HL4z/Vys=
Received: by filter0551p1iad2.sendgrid.net with SMTP id filter0551p1iad2-26912-5AB8B388-3
        2018-03-26 08:47:04.288035585 +0000 UTC
Received: from smtp.github.com (out-5.smtp.github.com [192.30.252.196])
	by ismtpd0008p1iad2.sendgrid.net (SG) with ESMTP id WDW7D6E3TaqRslBs4rNoxA
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:04.308 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:04 +0000 (UTC)
