### ISSUE TITLE
Data Mapper Extension

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis-project#106]
Creating an umbrella here as it may go beyond the datamapper.

* Requirements
  * Field-level actions contributed by user
  * Converters contributed by user
  * Packaged as iPaaS extension
  * Added to mapper UI as available action
  * Available to integration at runtime  

* Questions
  * when/how user upload it? within datamapper UI or somewhere else as a part of custom integration package?
  * Where do we store those custom field action and type converter and how do we carry it into the datamapper UI?

* Facts
  * atlasmap runtime is loading field actions and type converters using Java service loader 
  * field actions are provided via '/fieldActions' atlasmap rest API
  * there's also '/fieldMapping/converterCheck' rest API (looks incomplete, need to fix)

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (154/150 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-4.smtp.github.com ([192.30.252.195]:45531)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nmd-0013YX-Oo
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:16 -0600
Date: Mon, 26 Mar 2018 01:47:04 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054024;
	bh=DhkHMhPC2OQctn6w14r1sw6uRSZeCWvz+SJRHOxYXQk=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=vQ0DnoYp5kJ0+Z1vo2p6Fnu1PzqGs4DebSCHp8ySUz5R3d42lolDeX6bKmpmPRzka
	 lQQNn8vu5UQ+asdvnYOMYi3PjZTbTRDI8VR3X8ms6UXFDKjq/Apd/NhQmzAI/rd24u
	 Qqx8coSBvQAK03ZFb5gKe/hsCjlgOFZ7gCQkkgwg=
