### ISSUE TITLE
Builder pod fails when publishing integration

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#107]
I was able to walk through the entire scenario 1 with only a couple of issues that I was able to work around.  Once I publish the integration, the builder pod fails with "Generic Build Failed".  Based on the log output, it seems like the builder pod is getting killed.  No indication as to why -- possibly memory limit?

**Comment by dsimansk** [comment]
It seems that there are some default Maven opts propagated to BuildConfig of integration. Decreasing `Xmx` value to fit within current limits, e.g. `-Xmx200m` seems to resolve the issue.

```
      env:
        - name: MAVEN_OPTS
          value: '-XX:+UseG1GC -XX:+UseStringDeduplication -Xmx500m'
```

Cc @rhuss

**Comment by rhuss** [comment]
Yes, I could reproduce the issue 

![image](https://user-images.githubusercontent.com/99080/31095863-8f25e088-a7ba-11e7-8f2e-b570456b0a9d.png)

and it seems appropriate to restrict the Maven build via these options. Let me check where the options are set.

**Comment by rhuss** [comment]
Should be fixed by https://github.com/syndesisio/syndesis-rest/pull/665
