### ISSUE TITLE
Bad display of special UTF-8 characters in First name extracted from Github account

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-project#110]
I tried to log in to https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/dashboard
i accepted the application authorization on my github account and then my first name is badly displayed:
![image](https://user-images.githubusercontent.com/1105127/31130254-2954acf6-a857-11e7-8ea0-f3dcd395f8f6.png)

it is also badly displayed here:
![image](https://user-images.githubusercontent.com/1105127/31130309-51af6c40-a857-11e7-9495-ee9366bb9cef.png)

the character badly displayed is 'é'

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (158/150 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:48476)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nme-0013Yo-BZ
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:16 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=EDzTIWmyDnvH0lJ0Rrv5nkCY/UQ=; b=LZY4rbdqmXyhimrH
	dMmPZ79HH7ABSJKoBwJ+4AaNRvuoV0//ANffPmikT7WDeSLfCJb4f+yrvVZyS2DU
	Qh26ZSfwooT+phPlvAyQVJtrbSAYckxMxWxVyqUmwNkm7pTM4rNulSbrdu0GWiL4
	q11IjHcJoWQJy8nOP/ACrO1CJTc=
Received: by filter0371p1iad2.sendgrid.net with SMTP id filter0371p1iad2-15331-5AB8B388-17
        2018-03-26 08:47:04.605999409 +0000 UTC
Received: from smtp.github.com (out-2.smtp.github.com [192.30.252.193])
	by ismtpd0020p1iad2.sendgrid.net (SG) with ESMTP id KBaksb-8TpGrXLNtU6C9FQ
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:04.617 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:04 +0000 (UTC)
