### ISSUE TITLE
Empty validation message when creating a new Connection with invalid values

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-project#111]
![image](https://user-images.githubusercontent.com/1105127/31130584-17ea5c8a-a858-11e7-8d7e-7bf8e6ec06f7.png)

**Comment by gashcrumb** [comment]
@zregvart @rhuss looks like the response back from the verifier doesn't contain a description any more, any ideas?

Here's what I'm seeing:

```
[
  {
    "status": "ERROR",
    "scope": "PARAMETERS",
    "errors": [
      {
        "code": "ILLEGAL_PARAMETER_GROUP_COMBINATION",
        "parameters": [
          "clientSecret",
          "userName",
          "refreshToken"
        ],
        "attributes": {
          "GROUP_NAME": "USERNAME_PASSWORD",
          "GROUP_OPTIONS": "clientId,clientSecret,keystore,password,refreshToken,userName"
        }
      },
      {
        "code": "ILLEGAL_PARAMETER_GROUP_COMBINATION",
        "parameters": [
          "password",
          "clientSecret"
        ],
        "attributes": {
          "GROUP_NAME": "REFRESH_TOKEN",
          "GROUP_OPTIONS": "clientId,clientSecret,keystore,password,refreshToken"
        }
      },
      {
        "code": "ILLEGAL_PARAMETER_GROUP_COMBINATION",
        "parameters": [
          "password",
          "keystore",
          "userName",
          "refreshToken"
        ],
        "attributes": {
          "GROUP_NAME": "JWT",
          "GROUP_OPTIONS": "clientId,keystore,password,refreshToken,userName"
        }
      }
    ]
  }
]
```

On this particular page the UI is building that error box using `description` attributes from the response.

**Comment by zregvart** [comment]
I don't think we ever had `description` defined for `ILLEGAL_PARAMETER_GROUP_COMBINATION` type errors. Looking at the code that could add the description it never does/did that ([ResultErrorHelper.java#L105-L149](https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/component/extension/verifier/ResultErrorHelper.java#L105-L149)).

@lburgazzoli does it make sense for the ResultErrorHelper to generate description in that case or should we handle it in the verifier?

**Comment by rhuss** [comment]
@apupier btw, how did you end up at this screen ? Thought we all about OAuth these days, so never have seen this form with adding tokens since smiem ttime. Which connector are you using ?

**Comment by rhuss** [comment]
btw, I would also croak about the encoding issue with your name in top right of the screen ;-) wonder how we can fix that ?

**Comment by zregvart** [comment]
> Which connector are you using ?

this happens when you create connection for a credential (OAuth) based connector that hasn't been setup (no clientId/Secret)

**Comment by apupier** [comment]
> btw, I would also croak about the encoding issue with your name in top right of the screen ;-) wonder how we can fix that ?

I reported another issue for that https://github.com/syndesisio/syndesis-project/issues/110

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (165/150 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:27379)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nmg-0013ZL-LA
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:18 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=kRgJ8YHvo5Zl8RgDD+p9997bSCQ=; b=QEwhboE6qiLlTajg
	bprYst3OJieZUTMcMxOlwPphM1NdfK5gzJaziMs6wYRUjEs/6Q7ZDboav8Emt1cZ
	Q35R3HL9HP9v/qzNBueiTYlOFmhDlVhtDFkBDh7/AOvQY92Ekw2ZzEUPCfOuy8Gx
	tNllSKpslsjJ0YW0by/5bNrHmgg=
Received: by filter0469p1iad2.sendgrid.net with SMTP id filter0469p1iad2-6887-5AB8B388-1F
        2018-03-26 08:47:04.723350599 +0000 UTC
Received: from smtp.github.com (out-2.smtp.github.com [192.30.252.193])
	by ismtpd0007p1iad2.sendgrid.net (SG) with ESMTP id 6174ejg7QQK4BMSsplRuxQ
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:04.632 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:04 +0000 (UTC)
