### ISSUE TITLE
Error message when using dummy Salesforce connection

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-project#112]
on https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/integrations/create/action-configure/0/0

I tried a to create dummy Salesforce connection, then use it with "fetch record" , I got an error message "Please contact the administrator and file a bug report"

![image](https://user-images.githubusercontent.com/1105127/31130812-b88dcd0c-a858-11e7-93ab-6953d3eaf1aa.png)

**Comment by gashcrumb** [comment]
Yeah, that page actually needs to talk to salesforce, so a dummy connection isn't going to work at all.  Maybe we need to flag connections as validated or not so they're hidden from the integration editor until the user has actually validated that they work.

**Comment by apupier** [comment]
> Yeah, that page actually needs to talk to salesforce, so a dummy connection isn't going to work at all. Maybe we need to flag connections as validated or not so they're hidden from the integration editor until the user has actually validated that they work

Seems not very convenient to force to be in "connected mode".
What about use cases:
- service not yet available
-- started to design integration on spec
-- credentials not already available
- service down for a moment

but until the "non-connected" mode is available, having a message on this page explaining that we can't display information without a "validated" and "effective connection" would be nice (especially if a connection has been validated previous but the service cannot be reach at that time)

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (152/150 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-7.smtp.github.com ([192.30.252.198]:51950)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nmd-0013Yy-Fy
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:16 -0600
Date: Mon, 26 Mar 2018 01:47:04 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054024;
	bh=SSzri/utZor+wmchBc2lTy4MvXsqx7tRryWnmiNEaxE=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=TFI+dSfniv1m3x+2tfl6Rv7WawfT57wo1eZmYq4u/LEOsfKozwcuocAP42ob2/aNT
	 efvg2Gn0SHgiOzVLLzr5/dcDdof7vK/L0HZgeYb28I/sXPJ6hz4gIqYnkd/FZbNUBJ
	 bq2GFungPDLxhz3D0nkUoUsxN+pFHTzkKQzX7ZFo=
