### ISSUE TITLE
[Enhancement]provide a "Create new connection" on page to choose a Start Connection

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-project#113]
it will be nice to provide a shortcut to create a new connection if none is satisfying the user in the "Choose a Start Connection" page 

![image](https://user-images.githubusercontent.com/1105127/31130966-276d0bc0-a859-11e7-9d57-b8795c0971d4.png)

it will avoid user to go back to main menus, then Connections and loose on which project he/she started

**Comment by gashcrumb** [comment]
Yeah, the design calls for a 'create connection' card at the end of the list of available connections.

@dongniwang wonder though, would a 'create connection' button in the search toolbar be better?  Or both?  I guess the idea is the user has scrolled through the whole list and hasn't found the connection they want, so the last card is 'create a new connection' then?

**Comment by dongniwang** [comment]
Yes. We have a design with "create connection" card listed as the last card. 

And PatternFly [Toolbar](http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/) pattern actually includes a few action buttons in the toolbar area (see screenshot below). I think we can also include a Create Connection button to the right of the toolbar. The only thing is I would probably not make the button a primary action button (meaning do not make it the blue button). 

![image](https://user-images.githubusercontent.com/24943812/31132947-1b783cd6-a82c-11e7-82d8-5f0c9d5f701b.png)
