### ISSUE TITLE
Connector Generator REST Service

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#116]
The initial design and planning are scoped in this issue. The actual task depends on the parent's epics business story, but in essence, this issue is about a generic API for managing **Connectors** which is currently static and pre-defined in the database.

**Comment by zregvart** [comment]
It needs to accept:
 - Swagger document (uploaded/URL)
 - OAuth settings
 - name/description properties

**Comment by zregvart** [comment]
Swagger specification should be contained in the connector definition as one of the properties

**Comment by zregvart** [comment]
I think we have this in more details in the issues linked from #119. So I'll close this.
