### ISSUE TITLE
Tech extension UI management

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#123]

**Comment by rhuss** [comment]
Delete needs to check whether the extension is in use.

**Comment by lburgazzoli** [comment]
The UX design for Tech extension has been merged:

- https://github.com/syndesisio/syndesis-ux/issues/44
- https://github.com/syndesisio/syndesis-ux/pull/50
- https://github.com/syndesisio/syndesis-ux/blob/master/designs/technical_extensions/tech_ext.md

@gashcrumb @kahboom there is still some work to do on backend but can we start planning to implement the proposed design ?

**Comment by gashcrumb** [comment]
@lburgazzoli absolutely, let me review the designs and I'll start creating some UI issues to track the high-level items.
