### ISSUE TITLE
When login with github credentials, email is in username and email is empty

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-project#126]
I'm loggign in with my github account for the Red Hat account.

![image](https://user-images.githubusercontent.com/1105127/31430843-5f50dcf0-ae72-11e7-889b-db8b01d7827d.png)

**Comment by zregvart** [comment]
I think that screen will be removed when we go to TP2, so that won't be an issue.

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (151/150 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-6.smtp.github.com ([192.30.252.197]:56421)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nmd-0013Z7-HO
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:16 -0600
Date: Mon, 26 Mar 2018 01:47:04 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054024;
	bh=OaVGV3Sw2oGTLAk7mocN9fc0Ryy6T+z0ijnRCf4/578=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=QuQRcToFncvRTxqyVsKamYLonC99j9XR1MQ1Hl12jPyVQW6XSof2rgcu6u+LNeXEd
	 IFZnwNTEpIZr9pHrFPtkj4HDJZ0nS5nJDPOpbIFOSNFbofos1SlPQzSEVL2H2vJCjx
	 FZKwxbVv69SJpV0J/OqQi0nykccdnMYR1BaXj+YE=
