### ISSUE TITLE
Provide feedback on failing deployments

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-project#127]
currently if a deployment of an updated application is failing, there is no feedback to the user, there is even an "Active" state reported because the previous version is still working.

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (157/150 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:33414)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nme-0013ZJ-9i
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:16 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=9L91MS9qpNlu7kaWpuSSSQoBRpM=; b=DdTot0N3dsEi8oBZ
	VGCvoQaaaOpUNVtQuuURFm8qJQrL1MTE+MUTh72ylp1qg7wNfbKkr6rkAc/2e3rZ
	smVUAL+P2895svQs3bkSsPwjI6Ri1+rIqF54XYpB7Z+xurGFMki26+hULvApGFTV
	G7oInmwkGjj/b+TqfVUH2gUVUBM=
Received: by filter0394p1iad2.sendgrid.net with SMTP id filter0394p1iad2-24306-5AB8B388-21
        2018-03-26 08:47:05.056272382 +0000 UTC
Received: from smtp.github.com (out-5.smtp.github.com [192.30.252.196])
	by ismtpd0008p1iad1.sendgrid.net (SG) with ESMTP id o6HAG3m7SiCGpqbT4JzQzg
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:04.952 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:05 +0000 (UTC)
