### ISSUE TITLE
Remove KeyCloak

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-project#134]
Remove the KeyCloak dependency.  This should free up some memory and generally simplify things.

**Comment by chirino** [comment]
This epic is well underway to being done.  @jimmidyson took care of most of it.

**Comment by chirino** [comment]
While the current PRs associated with this Epic handle removing KeyCloak, we do seem to loose a little bit of UI eye candy around showing the user who is currently logged in.  We should create a rest service the UI can use to find out who the current user is.

I inspected the HTTP headers that the oauth-proxy is passing to the backend services and here's whats available.  Seem like it's enough to report back who is logged in:

![phpinfo__](https://user-images.githubusercontent.com/103255/31636588-12b6bfd8-b299-11e7-849a-bd02f213fc1c.png)

**Comment by zregvart** [comment]
FYI @chirino this has already been taken care of by @jimmidyson (see https://github.com/syndesisio/syndesis-rest/pull/694/files#diff-4199a31728ff0eb793a3fcaf04f3915bR83) -- with that we have Spring Security Authentication object that we can use for that rest service.

**Comment by jimmidyson** [comment]
I'm adding in a new REST endpoint `/api/v1/users/~` that will return a User object with relevant detaisl from OpenShift user - works nicely and just needs to be called on first load of the ui, after loading config.json - I can add that in too once this user endpoint is merged.

**Comment by jimmidyson** [comment]
I've just sent in a UI PR to use the new user API endpoint - works great.

**Comment by rhuss** [comment]
Done.
