### ISSUE TITLE
DB Connector

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#136]
TBD

**Comment by rhuss** [comment]
* A connection with a single Action (with parameters: SQL query, poll period)
* To be deciced:
  - Simple connector with plain SQL (that should be first moment)
  - Full DB select builder (which inspects metadata)
  - Expression language
* Datashape determined from database meta data and SQL statement.

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (150/150 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:61701)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nmd-0013Yc-K2
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:16 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=kILNi9Ndqd3WHL7kdtT81g3agD4=; b=Ef3xbQuJEEyEFjmQ
	vPuPopxcqZ3XVy+Qt1oNEm1pcZj6XsfclupFmhMDSvDVFmS0KVb0p7q9Nto8yJZ7
	pl+7KEzX/mlc0CfzYBNHw06YcSDbmOlt4OCAOkiPU3DNg5ERotWUNN+WxFrm1BY7
	Rm4pVUqL0EhpyxQkhmBTI3M+Zyk=
Received: by filter0043p1iad2.sendgrid.net with SMTP id filter0043p1iad2-7122-5AB8B388-E
        2018-03-26 08:47:04.405634611 +0000 UTC
Received: from smtp.github.com (out-5.smtp.github.com [192.30.252.196])
	by ismtpd0045p1mdw1.sendgrid.net (SG) with ESMTP id 5aR4Y3VLRt6JJA3fL1X5dw
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:04.342 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:04 +0000 (UTC)
