### ISSUE TITLE
OData Connector

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#138]
TBD

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (160/150 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:45737)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nme-0013ZU-Lp
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:16 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=YXFE+F1Gpo5PwF55X4MPmDI5vaw=; b=QvB3HaHtml0nEV3c
	K23Kf33r+8/rgU9RmaIT1I7IZsEL4wdwIqipaD3KO+ddu12KbycPXdKa9yeLQgV2
	lGcUqXPXIbU+BWVUEtHjYJp47X2AfYpKdIasSdlQ8WJjRKBk7Mxo6u1OqmTkiadB
	rRrvYYyAh3Z8IkQ8wPCvCPOfkXY=
Received: by filter0541p1iad2.sendgrid.net with SMTP id filter0541p1iad2-11229-5AB8B388-17
        2018-03-26 08:47:04.75226924 +0000 UTC
Received: from smtp.github.com (out-5.smtp.github.com [192.30.252.196])
	by ismtpd0008p1iad1.sendgrid.net (SG) with ESMTP id tsUUUCcFSkWjuI7sQrvZhQ
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:04.641 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:04 +0000 (UTC)
