### ISSUE TITLE
Upload interface to IDE

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#139]

**Comment by apupier** [comment]
@rhuss Can you precise what is the scope of this issue, please?

**Comment by rhuss** [comment]
@apupier  Acually this is about the rest endpoint for the upload tech extension from the IDE but could be of course the same as the upload from the UI. This issue is about nailing down the way how an IDE can communicate with Syndesis to manage tech extensions (including authentication) // @lburgazzoli

**Comment by nicolaferraro** [comment]
@paoloantinori you probably did some experiments on invoking syndesis APIs from curl.
Is there a way to use the Openshift auth token (what you get from `oc whoami -t`) to invoke the API, once syndesis app has been authorized?

**Comment by apupier** [comment]
related issue: https://issues.jboss.org/browse/FUSETOOLS-2630

**Comment by paoloantinori** [comment]
I have spent some time working on how to use Openshift oauth token without using the Oauth Proxy cookie.

I don't have a working solution yet, but it'd be on my to do list.

What I have done so far it's been to configure the OAuth proxy to delegate specific paths directly to Openshift authentication. This works, but Syndesis REST Springboot app than fails with the error in this linked case. I have to find the time to attach it to a debugger to verify what's the problem there.

https://github.com/syndesisio/syndesis-rest/issues/750

**Comment by lburgazzoli** [comment]
Closing this one in one, follow up on FUSETOOLS-2630
