### ISSUE TITLE
Support Dynamic Meta Data

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-project#14]
* Support providing selection lists dynamically. 
example: salesforce create or update contact action's twitter screen name field in the demo.

**Comment by rhuss** [comment]
Currently, the actions which can be selected for a connection are tightly coupled to the Camel Connector where the actions are associated 1:1 with the Camel connector. For dynamic actions, this association does not hold anymore.

Examples are the custom actions on SalesForce objects and the available stored procedures for Oracle EBS.

This story is about finding a solution for 

* obtaining the possible values for such dynamic action from a given connection. This requires a custom request to the backend.
* Configuring the connector during deployment time in such a way that the given action can be called at runtime. Is a generic 'salesforce-connector' which gets the action as parameter the proper way to go ?

@chirino  is this an appropriate description for this user story?
@zregvart @lburgazzoli @davsclaus any ideas what support would be required from Camel connector's side to support this requirement?

**Comment by rhuss** [comment]
This is related to #32

**Comment by jimmidyson** [comment]
We are now waiting on updates to UI and testing this works before closing... so close now...

**Comment by jimmidyson** [comment]
This is done! Nice work @zregvart @KurtStam and @gashcrumb !
