### ISSUE TITLE
Tech Extension kind

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis-project#149]
I'm wondering if extension should have a sort of flag to tell were they apply, I mean beside to contribute steps, we could have extensions that:

- contribute behavior to the integration (global error handler, etc)
- contribute dependencies to the integration (oracle db jar)

The UI then need to have a settings page when a citizen developer flags the needed extensions. 

@chirino @rhuss @kcbabo thoughts ?

**Comment by gashcrumb** [comment]
My gut feeling is keep the scope kinda narrow for starters, but lemme give it some more thought :-)

**Comment by rhuss** [comment]
@lburgazzoli I would also focus on the current use, but this doesn't mean that we in the future we could extend the format for the extension. It would be good if the manifes would carry a 'format version' number (e.g. like docker compose) to distinguish different format files. Also if we later can add stuff in a backward compatible way, that would be awesome. 

E.g. we could introduce a kind 'stepExtension' now and then later add to the list. But we as well could leave this out for the moment, and later, should we add this, just say "when no kind is given it defaults to a 'stepExtension'", which would be perfectly backwards compatible.

**Comment by lburgazzoli** [comment]
Of course didn't want to make it for the current use but just try to model the extension metadata and model that won't break (at least not too hard) when new scopes may be introduced :)

**Comment by dhirajsb** [comment]
@lburgazzoli since Camel can do a lot of things, it might help to put a fence around how far the extensions will go, i.e. how many and which features it will expose. A citizen integrator would not need to do everything an expert programmer could do with Camel. 

Trying to create an open ended extension mechanism might make it too generic, causing usage details to be pushed deep down the layers.
