### ISSUE TITLE
Provide a way to generate tech extension projects 

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis-project#153]
We should think about providing a tool to generate a tech extension project skeleton i.e.:

- https://launch.openshift.io/wizard/launchpad-new-project/1/e30%3D
- http://start.spring.io/

Tooling can the consume the same service.

**Comment by apupier** [comment]
the RHOAR project is planned to provide this kind of service for Red Hat Middleware stuff: https://access.redhat.com/products/red-hat-openshift-application-runtimes

**Comment by nicolaferraro** [comment]
I think that we can reuse whatever we do for FIS to generate quickstarts: maven archetypes, forge commands.

If we add a website for wizard generation, we should use it for FIS too.

**Comment by apupier** [comment]
Please note that using archetypes is no more continued for FIS, see https://issues.jboss.org/browse/OSFUSE-590
