### ISSUE TITLE
Camel HawtIO view for Syndesis integrations

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#157]
The OpenShift Java console (HawtIO) is available for integrations deployed from Syndesis, but it only shows the JMX plugin.  Would be awesome if the Camel HawtIO view was also available.

**Comment by dsimansk** [comment]
Camel plugin should be auto-loaded when Camel context is detected. Works for me on production cluster.

<img width="1145" alt="screen shot 2017-11-02 at 20 10 22" src="https://user-images.githubusercontent.com/5637792/32345384-486cf7ae-c00a-11e7-84d9-b45d1c3c4281.png">

**Comment by kcbabo** [comment]
Just verified it in my account as well.  I swear it didn't work before! :-)

**Comment by dsimansk** [comment]
The only difference I can think of right now is community image`fabric8/s2i-java` vs. productized `fis`. There might be some misalignment wrt to Jolokia agent.
