### ISSUE TITLE
AWS S3 Connector

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#158]
Include aws-s3 connector from syndesis-connectors into Syndesis backend.

**Comment by rhuss** [comment]
See https://github.com/syndesisio/connectors/pull/98 for the original PR.

**Comment by oscerd** [comment]
I've only updated the title :-)

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (156/150 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-6.smtp.github.com ([192.30.252.197]:37743)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nme-0013ZA-Ah
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:16 -0600
Date: Mon, 26 Mar 2018 01:47:04 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054024;
	bh=F2jS0Rex4aor3hABy6AC3NcWBSDzUdome2A604JG8BQ=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=xMMdxFU/Nw2rZKCA4pwC9GuCDd/FyObnvO4uF+HlDTwvqpKnfvrw0avNSmBFMfWf4
	 n4nmiPbMgPq+A50oc1d5gtR0b6pHqPpn0Isdod2FsagEFFEjr/Deu6jqnDHuMRqv/a
	 lSWhFruxwBfeuBTmGbAeL/9vyCVDQsw3doW9cZwE=
