### ISSUE TITLE
Tech extension: cleanup old extension

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis-project#164]
We should have a pluggable strategy to cleanup tech extensions.

First and default implementations should delete all extension except the active one and those that are in use.

**Comment by nicolaferraro** [comment]
Just thinking.. why should we leave "in use" extensions.. Is there need for a way for a integration to use a "logically deleted" extension?

The actual physical id of the package is not encoded in the integration, there should be only the "logical" one, right?

**Comment by lburgazzoli** [comment]
ok, we can keep only the latest one.
