### ISSUE TITLE
Tech extension: provide service to retrieve binary by extension id

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis-project#166]
There should be a service to retrieve the binary artifact associated with the extension given the extension (logical) id. This should be used by the project generator.

**Comment by nicolaferraro** [comment]
@lburgazzoli, [something like this](https://github.com/nicolaferraro/syndesis-rest/compare/add-extension-validation...nicolaferraro:jar-by-id-166)?

**Comment by lburgazzoli** [comment]
+1
