### ISSUE TITLE
Tech Extensions: align API to UI needs

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis-project#167]
Track PR: https://github.com/syndesisio/syndesis-ux/pull/50

**Comment by nicolaferraro** [comment]
I've looked at the ux design and compared with current definition of the API ([here](https://github.com/lburgazzoli/syndesis-project/blob/81049cdbe8e927cea5343469879bec1002eb8aa0/proposals/125-tech-extension.adoc) and [then](https://github.com/syndesisio/syndesis-rest/blob/35f4f4b2ba9a92d10f87d8e225f26b12084aa681/rest/src/main/java/io/syndesis/rest/v1beta1/handler/extension/ExtensionHandler.java)), and from my point of view the following changes are needed:

- Add a GET `/extensions/{id}/integrations` endpoint to retrieve all integrations where a specific extension is currently used
- Add a parameter (also a query parameter) named `updatedId` that contains the physical id of the extension that is being updated (see update process of the ux) to the POST `/extensions` service that accepts the multipart data. I'd not model the update as a PUT, because it creates a new `Draft` extension with a new physical ID. The parameter can be used by the backend during validation e.g. to ensure that the new extension has the same logical id (`extensionId` field) as the extension being replaced.


@lburgazzoli, @gashcrumb do you think that something else is needed? Are list filters handled directly by the frontend currently or they require something from the backend?

**Comment by lburgazzoli** [comment]
Only one note for point 1, we should return only id/name pairs to the ui to avoid transfer of uber jsons ...
