### ISSUE TITLE
Salesforce non DTO/JSON-compatibility mode

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-project#17]

**Comment by rhuss** [comment]
Should this be an epic or is it more part of a larger story (like the `Saleforces / Oracel EBS` user story https://issues.jboss.org/browse/IPAAS-324). Even when the story is important to multiples JIRA user story, I would attach it only to one (and keep the strict relation, ZenHub "Epic" == JIRA User Story)

**Comment by chirino** [comment]
Something to keep in mind is that changing the type of object flowing through camel might affect how it works with the filter step.

**Comment by chirino** [comment]
Seems the datamapper does not have json schema support yet.  We may need to generate example doc instead.

**Comment by zregvart** [comment]
I think we can close this, with #14 #16 and atlasmap/atlasmap#153 seems that we have this covered.

**Comment by jimmidyson** [comment]
Yep LGTM - thanks for the update @zregvart!
