### ISSUE TITLE
Fix Camel connectors to support connector component class properties

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis-project#171]
The current connector maven plugin only generates SpringBoot config classes if a base/delegate component property is exposed. It should also handle connectors that want to expose their own properties and should generate auto-config classes to allow configuring those.

**Comment by zregvart** [comment]
Don't we have that with `connectorProperties` JSON property?

For example [camel-connector.json](https://github.com/syndesisio/connectors/blob/f5614a775946b16420317b79a7d281850f65c190/connectors/sql-stored-connector/src/main/resources/camel-connector.json#L20-L93) generates [SqlStoredConnectorConnectorConfigurationCommon.java](https://github.com/syndesisio/connectors/blob/f5614a775946b16420317b79a7d281850f65c190/connectors/sql-stored-connector/src/main/java/io/syndesis/connector/sql/stored/springboot/SqlStoredConnectorConnectorConfigurationCommon.java#L22-L45)

Are we missing something, well other than docs?
