### ISSUE TITLE
As a citizen integrator, create an API connection

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#174]
As a citizen integrator, I want to create connections based on API connectors available in Syndesis.  When creating a new connection to an API, I need the ability to specify the endpoint URL for the API as I often need to connect to multiple instances of an API (different providers, different environments - dev/test/prod).  If the API connector has a default API endpoint URL (supplied via Swagger) then that should be the default value provided in the UI.  The endpoint URL should accept TLS and non-TLS endpoint URLs.

In addition to the endpoint URL, I also need to specify security details as defined by the underlying API connector.  Based on the connector being used, one of three options will be available for security-related configuration on a connection:
- No security
- HTTP Basic Authentication - I will supply username and password
- OAuth - offer the ability to initiate a web-based OAuth flow or supply OAuth details directly.

After specifying endpoint address and security details, I would like to verify connectivity to the API.  Syndesis should provide a default mechanism for validating the URL and security details are valid, but I would also like the ability to specify a specific action (e.g. GET) on the connection to be used for verification.

**Comment by kcbabo** [comment]
No. 2 of 3 issues related to API connector.

**Comment by zregvart** [comment]
@kcbabo I wonder if the citizen developer is the one specifying the authentication method, or if this should be done by the expert developer when defining the API connector (#173), and the citizen developer provides only the authentication material here (i.e. username/password, or performs the OAuth dance).
It does make it easier on us to have authentication method defined with the connector.

**Comment by kcbabo** [comment]
Great point.  I'm good with that approach.  I will adjust the stories accordingly.
