### ISSUE TITLE
Provide copy/paste callback URL for Syndesis on OAuth Settings page

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#184]
We force users to manufacture the callback URL now - would be much easier if we simply provided a copy/paste callback URL on the OAuth Settings page.  Having users manually create the URL from an example URL in the docs and their specific account URL is just asking for trouble.

**Comment by rhuss** [comment]
Issue moved to [syndesisio/syndesis #373](https://github.com/syndesisio/syndesis/issues/373) via [**ZenHub**](https://www.zenhub.com/)
