### ISSUE TITLE
How to improve handling of integration history?

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-project#20]
```gherkin
  Scenario: Camilla creates integration
    When "Camilla" navigates to the "Home" page
    And clicks on the "Create Integration" button to create a new integration.
    Then she is presented with a visual integration editor
    And she is prompted to select a "Start" connection from a list of available connections

    When Camilla selects the "Twitter Example" connection
    And she selects "Mention" integration action
    Then she is prompted to select a "Finish" connection from a list of available connections

    When Camilla selects the "Salesforce Example" connection
    And she selects "Create Opportunity" integration action
    Then she is presented with the "Add a Step" button
    And click on the "Save" button

#    try to publish without integration name will open basics page
    When Camilla clicks on the "Save as Draft" button
    And she defines integration name "My awesome first integration"
    And click on the "Publish" button
    Then Camilla is presented with the Syndesis page "Integrations"
    And Integration "My awesome first integration" is present in integrations list
```
![screenshot_20170613_165142](https://user-images.githubusercontent.com/8707241/27088679-a024919a-5058-11e7-96c7-b9b667645f82.png)

Now we let bob improve this integration
```gherkin
# Bob is also citizen developer, like Camilla
  Scenario: Bob will add log step to Camilla's integration
    When "Bob" navigates to the "Integrations" page
    And Bob selects the "My awesome first integration" integration
    Then He is presented with a visual integration editor for "My awesome first integration"

    Then Bob clicks on the "Add a step" link
    And he selects "Log" integration step
    And he types "just log my ${body} here!"
    And he clicks on the "Save" button
```
One would expect changes to appear in the original git repo, but instead we have new repo
which doesn' even contain the original commits
![screenshot_20170613_165424](https://user-images.githubusercontent.com/8707241/27088786-f61ad60e-5058-11e7-9e04-0e041d2eaba4.png)

**Comment by rhuss** [comment]
@jludvice could you please elaborate a bit on what you mean 'editing another users integration' ? Currently, we do not have a concept of authorization and everybody can edit everything.

**Comment by jludvice** [comment]
@rhuss I'm aware of that authorization (missing) concept, 
just need some time to write it in understandable way

**Comment by jludvice** [comment]
This should be considered together with https://github.com/syndesisio/syndesis-rest/issues/395

**Comment by jludvice** [comment]
For the reference, I'd expect original git repository to contain just one commit with changes like this:
```
 README.md                       | 2 +-
 src/main/resources/funktion.yml | 3 +++
 2 files changed, 4 insertions(+), 1 deletion(-)
```
```diff
diff --git a/README.md b/README.md
index a3a836d..68997f5 100644
--- a/README.md
+++ b/README.md
@@ -7,5 +7,5 @@ test integration
 To run this on OpenShift, just run:


-$ oc new-app fabric8/s2i-java:2.0.0~https://github.com/jludvice/base-jludvice-staging.git
+$ oc new-app fabric8/s2i-java:2.0.0~https://github.com/syndesisqe/base-jludvice-staging.git
 ```
```diff
diff --git a/src/main/resources/funktion.yml b/src/main/resources/funktion.yml
index 906801b..fe17109 100644
--- a/src/main/resources/funktion.yml
+++ b/src/main/resources/funktion.yml
@@ -3,5 +3,8 @@ flows:
 - steps:
   - kind: endpoint
     uri: twitter-mention
+  - kind: log
+    message: adfasdfasdf
+    loggingLevel: INFO
   - kind: endpoint
     uri: salesforce-upsert-contact
```

**Comment by jludvice** [comment]
For the reference, if I
* create integration >> new repo with 5 commits 
* edit integration and hit save >> additional 5 commits to this repo

Edit creates 5 commits (4 completely empty commits, 1 commit changing `funktion.yml`)

**Comment by rhuss** [comment]
@jludvice we are aware of this issue and tackle it with https://github.com/syndesisio/syndesis-rest/issues/395

**Comment by rhuss** [comment]
ehm, sorry. Just saw that you already has discovered the issue ;-)

**Comment by jludvice** [comment]
Np @rhuss :)
Does https://github.com/syndesisio/syndesis-rest/issues/395 cover also the part of editing integration by another user? 
We could probably close this issue if it does.

**Comment by rhuss** [comment]
Not yet, it's just focussed to get to a more 'normal' GitHub workflow. The story about versioning is more about the integration lifecycle (e.g. how we should version integration and also maybe to introduce a dedicated "deploy" action in addition to "save" as this deploying an integration is a quite heavy weight step.

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (176/150 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:5863)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nmk-0013de-Oh
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:22 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=6nCOY44rKXSQv5wCYaiEeXKPGks=; b=jJMET9095SgL7aDU
	Pr6O7GGDppO8sOdEYxvaUrG+gwKnloWd5xbgXyDTrK9McQi8YHaktQMWf+k/aaI4
	dMymthQr5gE84DN0TAQAUV8Dw0A1XBUMBaXAnGB5UjUXgwu2/QipzS1/HMK6uN4N
	pJGWh49jR1zBNWxSKz1E7FfVmDU=
Received: by filter1142p1mdw1.sendgrid.net with SMTP id filter1142p1mdw1-14722-5AB8B38F-1B
        2018-03-26 08:47:11.582612828 +0000 UTC
Received: from smtp.github.com (out-3.smtp.github.com [192.30.252.194])
	by ismtpd0029p1mdw1.sendgrid.net (SG) with ESMTP id sM-Xz8WPR728v-LSK6MmrQ
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:11.411 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:11 +0000 (UTC)
