### ISSUE TITLE
As a citizen user I want to know which version of my integration is running

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-project#21]
As a citizen user I tried to create and run simple integration.
Things things were pretty clear, now I want to go further.
I take the existing integration and
* add one step
* publish integration

How do I know when my changes become effective ?

Now I do some tuning and hit publish again and realize I broke my integration and I need to roll back.
I'd love simple "Back" button which would start previous version of integration.

Now I want to have stable version of integration running 
and I want to be able to test & run my new version until I'm satisfied with changes.

Once I'm satisfied, I want to replace my "production" integration with current dev version.

I already know this workflow from Red Hat BPM Suite and from 3scale api management.
It's possible to run multiple versions of one solution to allow smooth migration.

**Comment by jludvice** [comment]
It should be reasonably easy to implement this feature using
* git commits/tags on integration repository 
* and use openshift rolling updates based on those commits/tags.

What do you think about this @rhuss @jimmidyson @kcbabo ?

**Comment by rhuss** [comment]
The question is also _when_ this redeployment should happen. I argue for a dedicated "Redeploy" or "Update" button, so changes in the in the _Integration_ are committed when the user want it to be actions in one transaction. So actually we would also need at least _two_ views on an integration : The actively running one and the one which is currently worked on (and which should be in state draft). 

If we keep the OpenShift lingo this could be considered to be an `IntegrationStream` which encompasses multiple versions of `Integration`s from which a single integration is the active one.
