### ISSUE TITLE
Create Design Document for the Multi Web-API scenario

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#23]

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (174/150 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:7192)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nmk-0013d0-IF
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:22 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Tuki+jXXEq5GQ+UPIXVflgiom9A=; b=DR7xV0acvHcKjdHw
	bCKo3toAJ/jXe5V15NAZ7VqltN48wv5dRLRfSCECRcjjAERjIHdGS9VfhI8OgXPR
	ogX0W6/v/6TCuO2RckRsvwngXSUVjO2Gu1LuOI69/K4iMhjLsxiJCgI1gVjT74gF
	S7ZzQ4l/VmoQyr/GwcyzTVCh6aY=
Received: by filter0089p1iad2.sendgrid.net with SMTP id filter0089p1iad2-4036-5AB8B38F-A
        2018-03-26 08:47:11.282262321 +0000 UTC
Received: from smtp.github.com (out-5.smtp.github.com [192.30.252.196])
	by ismtpd0021p1iad2.sendgrid.net (SG) with ESMTP id Eokg5D5oTnqdtyuGZhpIcw
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:11.347 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:11 +0000 (UTC)
