### ISSUE TITLE
Multi Web-API integration scenario

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#24]
Sue creates a new API connection for each API she wants to integrate (API-1, API-2, API-3).  For each connection she creates, she is prompted on the connection configuration page to provide an Open API definition with all the configuration details for the API.  For one of the APIs, Sue accidentally imports an incomplete API definition, which is rejected by the iPaaS UI with details on what was wrong.  After correcting the mistake, Sue is able to create and validate the API connection.  With all three API connections created, Sue moves on to create a new integration.  Sue selects API-1 as the first connection and enables the option to invoke API-1 on a scheduled basis.  She then sees a list of actions that are based on the resources and verbs available in the API definition used to configure API-1 and selects a GET action.  Sue then selects API-3 as the finish connection along with an action based on the API-3 definition using POST.  She would like to use information from API-1 and API-2 when invoking API-3, so she adds an additional connection step to call API-2 with POST or GET (she's using some data from the API-1 result to call API-2).  She then adds a data mapping step between API-1 and API-2 in order to map data necessary to call API-2 from the data that's been received from API-1.  With the data from API-1 and API-2 in hand, Sue then adds an additional data mapping step between API-2 and API-3 which maps data from API-1 and API-2 into the final call of API-3.  At this point, the integration is complete and Sue publishes the integration to connect the three APIs.

**Comment by rhuss** [comment]
Superseded by #119 , but still useful as an example Scenario / Demo which could be used to be implemented by the API Connector.

wdyt, Zoran ?

**Comment by zregvart** [comment]
Overall it shows a lot of functionality so that is OK, otherwise it's bit too abstract for my taste. I think it would be better if we had concrete APIs that we're going to invoke in the demo, this way we would know all the mappings as a consequence and would know in time if we had any mapper requirements.
