### ISSUE TITLE
Salesforce to Oracle EBS scenario

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#26]
Tim creates a new Salesforce connection and initiates OAuth login flow.  As part of this flow, he provides Salesforce login credentials and grants access for iPaaS to operate on his account.  
With OAuth configured, Tim validates the connection prior to saving.  

Next, Tim creates a new connection to Oracle E-Business suite using a Stored Procedure connection.  He fills in the database connection parameters and login information, validates the connection and saves.  

Tim then creates a new integration and selects WebHook as the starting connection with the "Start Integration" action.  He then selects the Stored Procedure connection as the finish connection along with the "Invoke Stored Procedure with Parameters" action.  The resulting action configuration page presents Tim with a list of stored procedures available to the connection.  Next, Tim adds a connection step to the integration to call Salesforce whenever the WebHook is triggered.  He selects the "Query Custom Object" action and is presented with a list of all Salesforce objects available in his account.  Tim finds the custom object he wants and selects it, completing the action configuration.  

Tim is now ready to map the inbound Salesforce data to the stored procedure parameters that Oracle expects, so he adds a data mapping step.  Once the data mappings are created, the integration is complete and Tim publishes the integration to connect Salesforce and Oracle E-Business Suite.  

Tim needs to provide an external developer with the WebHook URL used to trigger the integration, which he is able to find on the WebHook connection details page in the iPaaS UI.

**Comment by jludvice** [comment]
Hi @rhuss, can I have silly question?
How is user Tim different from user Camilla? 
Is Tim more experienced? If so, in what areas?

**Comment by rhuss** [comment]
tbh, I just copied over the description from @kcbabo JIRA issue, but I think Tima and Camilla have the same level or experience.

But I leave the definitive answer to @kcbabo.

**Comment by kcbabo** [comment]
No difference between Tim and Camilla.   Just mixing it up with the names used.

**Comment by zregvart** [comment]
I think it's safe to say that this one is done.
