### ISSUE TITLE
As a citizen user, secure Twitter connections using OAuth

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#29]
As a citizen user, I want the iPaaS to handle authentication/authorization to my Twitter account using OAuth.  When configuring a Twitter connection, I want to be able to initiate an OAuth flow that I'm accustomed to with other apps where I login with my Twitter account and authorize iPaaS to access my account.

Validation of a Twitter connection using OAuth should include verifying authN/authZ using OAuth.

I should be able to change the account I use for OAuth for a Twitter connection after that connection has been created.

**Comment by kahboom** [comment]
Yes, it's finally happening. GitHub issues! GitHub issues!

**Comment by kcbabo** [comment]
High five!

**Comment by zregvart** [comment]
I think we're done here.
