### ISSUE TITLE
As a citizen user, search for Tweets using Twitter connection

### ISSUE THREAD

**Issue by jimmidyson** [syndesisio/syndesis-project#3]
Imported from https://issues.jboss.org/browse/IPAAS-321:
As a citizen user, I would like to have a search action for the Twitter connection which allows me to search for tweets with specific keywords. My searches will contain one or more keywords, so the UI should provide an easy way to add multiple keywords without requiring me to understand the search syntax.
Background info:
https://docs.google.com/document/d/1hAvHJLnIy66XyDmIC_zs3rJFj4pEd6cFrztbSHD1C28/edit#heading=h.vefh0v7vbd8o

**Comment by gashcrumb** [comment]
Start on this on the UI side -> https://github.com/syndesisio/syndesis-ui/pull/567

and linked issue -> https://github.com/syndesisio/syndesis-ui/issues/563

**Comment by rhuss** [comment]
@gashcrumb @KurtStam Where are we standing with this feature ? What still needs to be done ?

**Comment by gashcrumb** [comment]
@rhuss so on the UI side initially the thought was to use a tag list widget for the form input.  I have a widget in place that could be used but I haven't hooked it up to the code that generates the form yet, as it turns out the underlying input only needs a string with comma separated values.

That being said we could still use the widget as a way of ensuring the user consistently inputs multiple keywords and generate a comma separated string.  @dongniwang WDYT?  If so then maybe that particular field in the action could have a type of `taglist` or `list` so the UI would know to use the tag list widget instead of a regular text input, @KurtStam WDTY?

**Comment by rhuss** [comment]
I think a tag like a mechanism (with small 'x' to remove tags, too) and transparently translate them back and forth to a CSV list is nice, user-friendly way to add those elements. Even when they are not real 'tags' (because they are not reused across items).

**Comment by gashcrumb** [comment]
Hmm, staging doesn't seem to be working otherwise I'd post a screenshot of how the current widget looks in the app, until then here's their live example for playing around with -> http://www.buompris.co/ng2-tag-input/

**Comment by rhuss** [comment]
Staging should be again (at least its working for me ;-).

Yeah, such kind of interface is quite slick, and we should use it probably also in other places when the use cases arise.

**Comment by gashcrumb** [comment]
Is the URL https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/ still?

Also from a dev instance of syndesis-ui I'm getting:

```
VM219:1 GET https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/auth/realms/ipaas/.well-known/openid-configuration 503 (Service Unavailable)
```

in the js console.

**Comment by rhuss** [comment]
@gashcrumb It's https://syndesis-staging.b6ff.rh-idev.openshiftapps.com these days ...

**Comment by gashcrumb** [comment]
@rhuss thanks!  hey, has the clientId changed also? 

Anyhoo, here's how it looks in the context of the create connection step 3 form:

![download](https://user-images.githubusercontent.com/351660/27230347-eed41e8e-527c-11e7-877e-a342772dee01.png)

**Comment by gashcrumb** [comment]
@rhuss BTW, new staging URL works but a dev instance of syndesis-ui doesn't, have updated the clientId appropriately but am getting:

```
XMLHttpRequest cannot load https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/auth/realms/ipaas/.well-known/openid-configuration. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.
```

when hitting it.

My `config.json`:

```
{
  "apiEndpoint": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/v1",
  "title": "Syndesis",
  "datamapper": {
    "baseJavaServiceUrl": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/v2/atlas/java/",
    "baseMappingServiceUrl": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/v2/atlas/"
  },
  "oauth": {
    "clientId": "syndesis-ui",
    "scopes": [],
    "oidc": true,
    "hybrid": true,
    "issuer": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/auth/realms/ipaas"
  }
}
```

@kahboom FYI

**Comment by rhuss** [comment]
@jimmidyson you probably know the answer to this issue immediately. I would have to search for (but will do if you are busy or dont know it by heart)

**Comment by jimmidyson** [comment]
@gashcrumb Can you please try:

```
{
  "apiEndpoint": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/v1",
  "title": "Syndesis",
  "datamapper": {
    "baseJavaServiceUrl": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/v2/atlas/java/",
    "baseMappingServiceUrl": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/v2/atlas/"
  },
  "oauth": {
    "clientId": "syndesis-ui",
    "scopes": [],
    "oidc": true,
    "hybrid": true,
    "issuer": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/auth/realms/syndesis"
  }
}
```

Changed issuer URL to syndesis suffix.

**Comment by jimmidyson** [comment]
BTW you can just use the one from staging if you want (which is virtually the same as above, although different scope - I can't remember why) - https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/config.json.

**Comment by gashcrumb** [comment]
Missed that one, thanks!  Next problem :-)  It doesn't seem to like the redirect_uri param, I hit a `we're sorry` page instead of the login prompt.  Do we have https://localhost:4200 as a valid redirect URI at the backend?

Also just so @kahboom can copy/paste the config:
```
{
  "apiEndpoint": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/v1",
  "title": "Syndesis",
  "datamapper": {
    "baseJavaServiceUrl": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/v2/atlas/java/",
    "baseMappingServiceUrl": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/v2/atlas/"
  },
  "oauth": {
    "clientId": "syndesis-ui",
    "scopes": [],
    "oidc": true,
    "hybrid": true,
    "issuer": "https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/auth/realms/syndesis"
  }
}
```

**Comment by jimmidyson** [comment]
@gashcrumb Try again...

**Comment by gashcrumb** [comment]
Almost, now hitting CORS errors for the rest API...

**Comment by gashcrumb** [comment]
Hmm, actually getting a 403 response for those requests too :-/

**Comment by kahboom** [comment]
Ty @gashcrumb , testing now

**Comment by dongniwang** [comment]
Sorry for the late response. But yes, tag like mechanism works fine. @gashcrumb

**Comment by rhuss** [comment]
What is the current state of the overall story ? Are there still things to do in the frontend / backend ? Can it be already tested ?
