### ISSUE TITLE
As a citizen user, secure Salesforce connections using OAuth

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#30]
As a citizen user, I want the iPaaS to handle authentication/authorization to my Salesforce account using OAuth.  When configuring a Salesforce connection, I want to be able to initiate an OAuth flow that I'm accustomed to with other apps where I login with my Salesforce account and authorize iPaaS to access my account.

Validation of a Salesforce connection using OAuth should include verifying authN/authZ using OAuth.

I should be able to change the account I use for OAuth for a Salesforce connection after that connection has been created.

**Comment by zregvart** [comment]
I think we're done here.
