### ISSUE TITLE
As a citizen user, I want to schedule connections instead of using a Timer

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#33]
As a citizen user, I would like to trigger an integration to connect using a Start connection at periodic intervals.  This is possible today using Timer as the Start connection, but feels a bit odd.  It's counterintuitive when creating a new connection and is confusing when I view connection lists and see Timer as the 'from' connection which has nothing to do with the actual source system.

What I would like to do is select a connection the real connection and action I'm interested in (e.g. Twitter search) and then mark it directly as scheduled.  Configuration of the schedule should be similar to what Timer connections provide today.

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (177/150 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:5245)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nmk-0013dt-R6
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:23 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=VfpO/KTRrKRmHatyBwA+98CRiCE=; b=XkUKGiOTWgZ5WLld
	bC5Y9r8BklbArUMNEIvfdUjt62b+Z3sT7x2zvI/XLPvFNln6UpaPHF8bUsl3/Ojq
	SU064DzVOYKWec0VS2JhcVPK0uciWuWqmftoXDSabsaCJ96YGFbSO1oGG/18bcQO
	8q9sey+BWQ74dpyo5PyS57iinX4=
Received: by filter0615p1iad2.sendgrid.net with SMTP id filter0615p1iad2-1887-5AB8B38F-15
        2018-03-26 08:47:11.713034893 +0000 UTC
Received: from smtp.github.com (out-2.smtp.github.com [192.30.252.193])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id e-lEA6amReaaJOkrzNSBFw
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:11.603 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:11 +0000 (UTC)
