### ISSUE TITLE
As a citizen user, connect to an API based on a OAI/Swagger definition

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#34]
As a citizen user, I would like to create an API connection based on an Open API definition.  The API definition should configure the connection with the API endpoint address and create actions for each resource/verb defined.  The data model for the API requests and responses should be associated with each action when available so that type-aware steps (data mapper, filter) can operate on that information.  If a resource path includes parameterized values (e.g. {id} for a GET request) then that should also be available to be set via configuration and/or data mapping.

API configuration should include support for security, with SSL/TLS as a supported transport and basic and token-based authentication.

**Comment by zregvart** [comment]
Let me just point out the [Swagger REST Camel component](https://github.com/apache/camel/blob/master/components/camel-rest-swagger/src/main/docs/rest-swagger-component.adoc) that can be used to implement much of the required.

**Comment by rhuss** [comment]
Superseded by #119 , linked as reference.
