### ISSUE TITLE
As a citizen user, allow integrations to be triggered via WebHook

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#35]
As a citizen user, I would like the ability to trigger an integration through an external HTTP request to a well-known URL.  When creating an integration, I would select WebHook as the start connection and specify whether data is accepted via the WebHook.  If data is accepted, I should have the option of defining the type of that data via JSON or XML schema.

Integrations triggered via WebHook must have a publicly available URL endpoint which can be discoverable via the iPaaS UI so that this information can be passed along to clients invoking the WebHook.

**Comment by rhuss** [comment]
@kcbabo @zregvart I wonder where this story fits. Is this part of the "API Client connector" #119 Currently in the API client connector everything is focussed on _outgoing_ connections, not incoming. 

Is this an extra story (and if so, how should it be prioritized ?) or is this part of #119 ?

**Comment by zregvart** [comment]
I don't think this is a part of #119.

**Comment by kcbabo** [comment]
Agree with @zregvart.  I view this story as a degenerate case of API provider - basically exposing an HTTP URL that can be used to start an integration.
