### ISSUE TITLE
As a citizen user, use a connection to invoke a DB stored procedure

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#37]
As a citizen user, I would like the ability to invoke a stored procedure in a database using a connection.  When creating a stored procedure connection, I will provide the connection details and login information to access the database with the stored procedure I want to invoke.  At the time the connection is used in an integration, I should be presented with an action that lists the stored procedures available in the database and allowed to select one.  The parameters of the stored procedure should be available as a first class data model in iPaaS so that I can use type-aware steps like the data mapper to map data into the parameters.

Validating the stored procedure connection should verify connectivity to the database and that my account has the rights to list and describe stored procedures.

**Comment by rhuss** [comment]
Hi @KurtStam it would be awesome if we could start with this story already in this sprint, best already this week. I'm on PTO for the rest of the week, but I'm probably of not much help anyway. Please talks also with @chirino as we were in the last meeting with it where it looks like that this part of the integration is quite forward.

I would love to know, how we can setup a test and access some test backend system from our staging environment. If we could achieve this in Sprint 15 would be awesome.
