### ISSUE TITLE
Publish -> Active should take less than one minute

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#39]
For the scenarios we ship for PR1, each integration should be able to be deployed in less than one minute. This time is measured from the user clicking "Publish" to the integration state changing to Active.
Assumption here is that 'Active' means the integration is really running.

**Comment by jimmidyson** [comment]
We need to measure this to see if we need to deploy a centralised Maven cache (Nexus probably) to speed this up.

**Comment by rhuss** [comment]
I will check that and make some tests on our OSO Pro account. The other idea was to bake a base image for TP1 which contains the Maven deps already in ~/.m2. Of course, this we can still do as a 'last minute fix', too (as this enhanced base image is very likely not to be productised)

If we do install a central Nexus, where would it run ? It for sure doesn't fit into the per-project budget, so would need to run elsewhere in another central namespace on OSO Pro (so we would need yet another account for it).

**Comment by rhuss** [comment]
Ongoing work, keeping it for Sprint 19 to stay focussed.

**Comment by chirino** [comment]
I've started a s2i image that bakes in all the mvn deps into the ~/.m2/repository directory at:
https://github.com/syndesisio/syndesis-s2i-image
https://hub.docker.com/r/syndesis/syndesis-s2i/

I think this should help shave off some time off the build. Still need to update the templates to use this instead of the FIS s2i image.

**Comment by rhuss** [comment]
We should not forget to start a productisation process of the image if we decide to settle on this.

**Comment by chirino** [comment]
Once TP2 is out we should merge https://github.com/syndesisio/syndesis-openshift-templates/pull/138 

Dev should then get quicker builds for integrations.  In TP3 we can work on adding the new image to the prod pipeline.
