### ISSUE TITLE
Stabilise CI infrastructure

### ISSUE THREAD

**Issue by jimmidyson** [syndesisio/syndesis-project#4]
We need stable PR tests so we can get faster and more accurate feedback to help us ensure that PRs don't break Syndesis.

This includes stabilising the Jenkins deployment and ensuring that the e2e tests run for each PR to each of our repositories, not just for REST project.

Bonus points for figuring out a way to trigger a merge build, i.e. a build that runs immediately before merging a PR. This should be a queue with no concurrent builds that merges the PR if it runs successfully. Reason for this is that PR tests could have been run against a previous HEAD so might be out of date.

**Comment by rhuss** [comment]
@iocanel Is there a rough estimation when we can close this issue ? Beside the probe timeout issue, are there any other oustanding issues which we should trach here, too ?

**Comment by iocanel** [comment]
@rhuss: Once we are able to resolve the probe issue, we will return to the state were we were before the re-branding: `We will be able to run simple system tests, that verify that we are not terribly broken. In other words that pods are able to start`.

The next step is to become serious and replace our system tests (that are really limited) with the end to end tests suites that @dsimansk and @jludvice are working on. 

At the moment e2e tests are blocked by, the fact that each oauth application is bound to a fixed url. Which means that we are restricted to running a single pipeline at a time, unless we are able to create oauth apps on demand, or somehow manage a pool of oauth apps.

**Comment by rhuss** [comment]
Ok, I see the point. Do we want to keep this issue open until the OpenShift dedicated problem is solved via an update ? I.e. when https://errata.devel.redhat.com/advisory/29143 has been released and updated on our installation ?

I will move to Milestone #14 nevetherless.

**Comment by jludvice** [comment]
+1 for leaving issue open until we have working infra

**Comment by jludvice** [comment]
Hello I hope you don't mind me adding 3 issues related to jenkins config to this epic.

**Comment by jludvice** [comment]
@iocanel can you please take a look?

**Comment by jludvice** [comment]
Hi @rhuss, wouldn't it make sense to leave this issue open until all 3 subtasks are resolved ?

**Comment by rhuss** [comment]
Ah, yes. Lets keep it open, I overlooked that there are still ongoing subtasks.
