### ISSUE TITLE
Integration tracing

### ISSUE THREAD

**Issue by jimmidyson** [syndesisio/syndesis-project#45]
In time, users will want to see traces of their integrations to look for bottlenecks, etc. In line with other projects strategies, we should probably use OpenTracing via Jaeger, which is supported by Camel [OpenTracing component](https://github.com/apache/camel/tree/master/components/camel-opentracing).

**Comment by jimmidyson** [comment]
I will submit a short proposal for this, but already have an implementation that works nice and simply (was playing with tracing recently).

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (179/150 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:29465)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nml-0013eK-1j
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:23 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=DZNPM2XOD0oVH0dyzbon/UeTHc8=; b=XjR4XgFj/8gaJOfH
	G6Aolkva76ZGmeaZ7qdp0rNoSI6NGnYuq9S7sbySJM3IZdlYqLlYoF08AF9qJpJZ
	UcIVp5hrw14Fn7rC+Vulbu5FZwM7epCLAOrI9ECo9P8o2ovvfcOWXV1EEyM5MpQF
	yFCt6zMnTIRbSpOUQ+aG192oXWk=
Received: by filter1251p1mdw1.sendgrid.net with SMTP id filter1251p1mdw1-29800-5AB8B38F-17
        2018-03-26 08:47:11.845833401 +0000 UTC
Received: from smtp.github.com (out-2.smtp.github.com [192.30.252.193])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id oTFGNsGGTJaAgU8rxnP8rg
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:11.892 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:11 +0000 (UTC)
