### ISSUE TITLE
Examine using contracts between UI and the REST backend

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-project#59]
[Spring Cloud Contract](http://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html) is something I've used before it consists of JSON files generated to define the REST API interface. From that you get stubs that can be used to develop the UI against but also tests that can be used against the backend implementation.

Perhaps create a demo PR to help evaluate it.

There is also [Pact](https://docs.pact.io/) and [Pacto](https://thoughtworks.github.io/pacto/).

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (166/150 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-5.smtp.github.com ([192.30.252.196]:40576)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nmj-0013bf-I5
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:21 -0600
Date: Mon, 26 Mar 2018 01:47:10 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054030;
	bh=AI0bf8LEqh4PqH17x8ytElNJzXYrewe+7yuBBn6VhQ0=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=vUqQyq3XKAJeE/ysACoDQwfWzCNJA4qnL+jNjxGT+dZuU74KagX93yls5Z4/uRzel
	 09qxat0CBKZn/NkZV5IktFod+XaPxV6ja86rn5rN6ud1UGiZVrAULabGDklN1pWPaN
	 ITK52E1iRoAV4+1R3MG8xVJCFFhwjREmxcEjartU=
