### ISSUE TITLE
Tag and release code and images at end of each sprint

### ISSUE THREAD

**Issue by jimmidyson** [syndesisio/syndesis-project#61]
As discussed on IRC, we should tag each repository at the end of each sprint, push tagged images, have openshift templates that use the tagged images, and update a demo site hosted at https://demo.syndesis.io.

This should include release pipelines in each affected repository.

**Comment by dsimansk** [comment]
@jimmidyson I'm happy to help with any kind of tag&release effort. Just let me know :)

**Comment by rhuss** [comment]
Maybe within Jenkins build ?

**Comment by jimmidyson** [comment]
Yeah I've started looking at it briefly

**Comment by iocanel** [comment]
This has been implemented. The release jobs on Jenkins do proper releases for maven artifacts and push images to dockerhub.

At the moment we don't do that for syndesis-ui. I need help in that front (we need an openshift way of building the project).

Other than that I think we can close that. @rhuss  @jimmidyson. wdyt?

**Comment by rhuss** [comment]
For me it looks good and I think we can close the issue.
