### ISSUE TITLE
Prepare initial list of image to productise

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#62]
We need an initial set of images which we already can productise.

See https://issues.jboss.org/browse/ENTESB-6963 for the original ticket.

Our current set of images are:

* syndesis/syndesis-rest
* syndesis/syndesis-ui 
* syndesis/token-rp
* atlasmap/atlasmap
* syndesis/syndesis-verifier
* jimmidyson/keycloak-openshift
* jimmidyson/pemtokeystore

plus their base images.

@jimmidyson can we move the keycloak and pem converter image to syndesis, too?
@syndesisio/backend which would be a good initial set so that we can already start to exercise the productization process?

We might need to adapt our base images to productized images:

* FIS Java S2I images for our Java services
* Nginx instead of Caddy for the UI as Nginx is already available as a product image ?

Maybe we can start with syndesis-rest, atlasmap and syndesis-verifier as these are all similarly structured, java based images ?

**Comment by jimmidyson** [comment]
Happy to move keycloak-openshift but pemtokeystore would like to keep where it is as it's used by some other people/projects if you don't mind.

**Comment by rhuss** [comment]
@jimmidyson No problem at all to keep pemtokeystore in your repo. 

I'm just wondering as every extra image for productisation adds some process burden, wouldn't it be easier to inline pemtokeystore in our images (e.g. calling it as part of the startup script of our apps) ? Actually for a long to mid term goal we could try to get this functionality to the base java images (e.g. add it to run-java.sh), community and product.

wdyt ?

**Comment by rhuss** [comment]
This is done.
