### ISSUE TITLE
Nexus SSO with OpenShift

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-project#63]
Nexus supports [SSO](https://books.sonatype.com/nexus-book/reference3/security.html#remote-user-token) via header, [openshift-auth-proxy](https://github.com/fabric8io/openshift-auth-proxy) can provide that header.

**Comment by jimmidyson** [comment]
Wow openshift-auth-proxy is a thing of beauty - wonder what genius came up with that idea? :wink:

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (168/150 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-3.smtp.github.com ([192.30.252.194]:33503)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nmj-0013c1-Mh
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:21 -0600
Date: Mon, 26 Mar 2018 01:47:11 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054031;
	bh=UEZ4VsGSLrBBqnmvsVIvu57QWdIL7qGiYIJ0oDWz+Is=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=iWZ3ovOzSiJ4ZMGES0Y+B227tgdAcfM3n1nz2kszinvmaNFQk1ax3zwytZ674Msxm
	 Np/TZ0+l40bQVLlHAqJFMlCs8u257iNaJL11eMcF6rgik+56CLAr+h+LDX/q7Q7W6J
	 e3ZQ3avu5kwAT6l0KvDpErTle+q1B2yeHxCoATTg=
