### ISSUE TITLE
Integration Editor steps position validation and feedback

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-project#66]
Background story: going through the Integration Editor for a couple of times and miss-clicking here and there got me thinking if we should be more strict in a way we allow user to create "routes". This proposal should capture positioning and boundaries of Connections+actions in which they can be used.

Our predefined Connections + action wrapping, in a nutshell Camel component+config+action, has already narrowed scope of usage and placement in the Camel route itself. Therefor it would be beneficial if we enforce  a few rules in regards to creating new Integrations. Some of these rules are already captured in metadata of our Connectors, see the example `pattern` property of [Twitter Mention](https://github.com/syndesisio/connectors/blob/master/connectors/twitter-mention-connector/src/main/resources/camel-connector.json#L15).

Deriving from the above statements, there's no point to start your Integrations with `Salesforce Create Contact` or the way around end it with `Twitter Mention`. Our editor should apply simple rules and "integrations patterns" to guide citizen devs through the process and maybe teach them by example, by providing immediate feedback about wrongly chosen elements etc. 

Couple of simple rules:
- check `Pattern` property as a validation step of Integrations
- don't allow `To` pattern to be used as route start
- don't allow `From` pattern to be used as route end 

@kcbabo I think we need to validate this requirement and afterwards scope the priority. I suppose something like after TP1 is more viable options.

CC @rhuss

**Comment by kcbabo** [comment]
I agree with the requirement to not allow users to do things that clearly won't work.  We should protect against this in the UI and test for it to validate the behavior.

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (181/150 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:30951)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nml-0013ea-Ao
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:23 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=oHEcrX2j+YpSMQIRhWxjW+k0X9k=; b=UzpFgvysJM9MMkNz
	vdC6PvJFADLrexuDoIArCqkuSFNNCOfiebcSztgPgMFSaaQcYxGJPVZpuAG9hMJJ
	qI69/Lh+CUbuW985G1dBsL7QMfrRJxygkcOed1HPp81mrAQRGVD8Rwt5V7ncWvbn
	zpo/osx64YmlZR7Hnf62bRlXetw=
Received: by filter1089p1mdw1.sendgrid.net with SMTP id filter1089p1mdw1-5657-5AB8B38F-12
        2018-03-26 08:47:11.353154536 +0000 UTC
Received: from smtp.github.com (out-2.smtp.github.com [192.30.252.193])
	by ismtpd0048p1mdw1.sendgrid.net (SG) with ESMTP id j6TV3LeDTFeUF3FCgTZOQA
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:11.328 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:11 +0000 (UTC)
