### ISSUE TITLE
Integration Summary Page link to source code

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-project#67]
Based on UX design https://github.com/syndesisio/syndesis-ux/pull/14 and related discussion. 

> It feels like minor improvement, but further down the road when we'd like to include some IDEs to the mix, migration etc. we could just display Clone or Download button similarly to GitHub.

Among the details we're going to provide on Integration Summary Page we should also include link to the source code itself. We can start with simple hyperlink to the GitHub repo and further expand it to more refined button that generates git clone link or download zip button.

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (173/150 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:38925)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nmk-0013dA-Gf
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:22 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=jvkPrEGaQ45/9rAYDsXTX0ZZnhI=; b=ofSGGALLMDO11BJ3
	tfR1q3mtFBYatzqT7FVOMWa/qjXN2mzcSEnMhLD7etrRL2BNm5l6FZeGn5ApZ62F
	yOr36urKA4hmHeGjTqXBzh+JbgTEc2WSsk7ZWQLmvT23Ni/S9YkwEkeTL2ja09Ql
	ycyrPsNbNT2YSPaVTkDUK1/5Jxw=
Received: by filter0214p1iad2.sendgrid.net with SMTP id filter0214p1iad2-18607-5AB8B38F-13
        2018-03-26 08:47:11.591837755 +0000 UTC
Received: from smtp.github.com (out-5.smtp.github.com [192.30.252.196])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id MdyZF8RbRtCOMMczz_nIAQ
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:11.296 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:11 +0000 (UTC)
