### ISSUE TITLE
Technical Preview 1 Onboarding Plan

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#68]
This is a brainstorming issue about how should the onboarding / offboarding procedure for registered should be performed technically. This should result in a list of tasks to perform for the onboarding process.

* How to manage registration requests (e.g. spreadsheets ?) ?
* Installation script for setting new users ?
* Monitoring usage ?
* De-installation script ?
* Communication with users (automatic mails, mailing-lists, forum) ?
* Registration page ? 
* Feedback form ?

@syndesisio/all The goals is to have a plan for the onboarding process at the end of this sprint 15. Please add your thoughts and ideas to this issue.

**Comment by dsimansk** [comment]
What about following Obsidian's approach? https://launch.openshift.io

And maybe reusing similar wizard https://launch.openshift.io/wizard/launchpad-new-project/1

**Comment by rhuss** [comment]
Good idea, @dsimansk 

As this is more about productisation than the project itself, I opened a JIRA issue at https://issues.jboss.org/browse/IPAAS-339

Let's followup the discussion there (but keep this issue open as a reminder)

**Comment by jludvice** [comment]
EDIT: comment moved to jira

**Comment by chirino** [comment]
BTW.  We have the option to be able to install the ipaas on a **per user** project which we get OCP admin rights on but the wont be able to manage.  This would let us install manage and teardown directly and giving the user a more SaS experience.  I think a part of openshift.io is managed this way.

We would likely need to build an app to manage all the ipaas project deployments as it would be too error prone to manage user's ipaas project each by hand.

**Comment by kahboom** [comment]
This should also include the documented user walk-through, or guided tour: https://github.com/syndesisio/syndesis-ui/issues/57

**Comment by kahboom** [comment]
I'd also recommend having issues for each feature as part of the FTUE (well, at least for the UI I find it helpful as opposed to several PRs in the case of such a big, overarching task), but whatever works for everyone else is fine with me.

**Comment by kahboom** [comment]
@rhuss @jimmidyson  - A few questions:

1. Are we wanting to persist the on-boarding experience for first time users to the REST API? i.e. If a user has already started the guided tour, what step they are on, if they've selected to opt out of it. If so, we will need another REST API endpoint, which I can add to the proposal. If so, do I just write whatever data model I want for this situation in JSON format or is there something specific you'd need?

2. Will the documentation we were discussing in the other issue (for tooltips or even the guided tour, from an AsciiDoc file, extracted via a Maven plugin) be provided as JSON from the REST API? Assuming we will need yet another endpoint here as well.

Thanks! :)

**Comment by rhuss** [comment]
1. I don't think that we should persist the steps server-side. If required, the step states should be stored client side.

2. I'd prefer to have the tooltips pre-generated into the syndesis-ui repo, e.g. as part of the build process. This step should fetch a JSON file from e.g. raw.github.com and then put it into syndesis-ui so that it can be committed. This would avoid any latency and connection issues to the backend and is the most performant one. You can safely assume that you will have a tooltips.json as static file.

**Comment by kahboom** [comment]
On second thought, I'd guess the only important thing to persist in terms of #1 is whether or not this is the first time they've logged in, as it would be ideal that users be able to re-start/close the guided tour at any moment either way, so it should mostly be done on the front end, but we'd still need to know if it's the user's first time logging in.

**Comment by kahboom** [comment]
Ah just saw your response @rhuss , thanks! Do we have an example of what the format of that tooltips.json will contain? We could likely use something similar for the guided tour, but we'll just store that in the client in the front-end I guess.

**Comment by rhuss** [comment]
@kahboom I was asking the same question in https://github.com/syndesisio/syndesis-documentation/issues/20#issuecomment-324864201 so not sure yet. I try to figure this out tomorrow.

**Comment by rhuss** [comment]
Now that we are at TP1 I think that can be closed. The open tooltip discussion has been already tackled with the introduction of a maven plugin which needs to be activated for the build still. There is open issue syndesisio/syndesis-documentation for this.
