### ISSUE TITLE
As a citizen user, start integrations based on Salesforce events

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#75]
As a citizen user, I would like to trigger integrations based on events that occur to objects in Salesforce.  When creating an integration that starts with a Salesforce connection, I want new actions for:

- Object updated
- Object inserted
- Object deleted

Configuration for these actions should include the ability to select the type of object to monitor based on a dynamic list of objects available in my Salesforce instance.

**Comment by zregvart** [comment]
This has been implemented via https://github.com/syndesisio/connectors/pull/69 and https://github.com/syndesisio/syndesis-rest/pull/621
