### ISSUE TITLE
Data Mapper UI is showing internal fields

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-project#76]
While playing around with the data mapper in the the Twitter to Salesforce scenario, I noticed that there's a new DESCRIPTION field in the root tree of the Salesforce Contact object.  This looks to be an internal data mapper or serialization-related field.  We should probably look to see where this is coming from and consider screening it out.

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (175/150 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-4.smtp.github.com ([192.30.252.195]:57861)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nmk-0013cp-Og
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:22 -0600
Date: Mon, 26 Mar 2018 01:47:11 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054031;
	bh=DRdpkOswrsPgcfJCJdhSyCSf2jaZCc88Cnnsgf6HH/U=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ggRQV45MOjvcIH8yYUQ+8aO/mDsuavmpRFsJdSOq/I1qfNaNNlZiKvFamLk7oFKds
	 ksC1pEXS3eZ1P6kk2ozO3LJriBgFxLdRe1cmnPgQXc5bcBBjtW1mkKUpKdXWURWuls
	 E+rij5mLAhyEgDAS2eRUi/G1i35jROQARA2M1GZU=
