### ISSUE TITLE
Support metadata in (the new) `syndesis-verifier`

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-project#81]
Along with connection verification we need to support the retrieval of metadata in the `syndesis-verifier`

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (184/150 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:33650)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nml-0013eH-MA
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:23 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=lyg/8M/38HLkvKhJCWM15Hu2MYk=; b=d1um/ED8abpaLmii
	40nc5Bz+RJoRqBl8zKeuy9Mz5kk7hDWanw6aLHD71I/PUuRNbt7gXC8VeP6GgXcQ
	mPidhCNr4hNop2TR0BwsRXovAgJU6tL67VRlZvy1g5OEsmC9Mu4o21/EYP14zvPm
	sXds3b8aexn0HaamUIqYyD0rzxU=
Received: by filter0632p1mdw1.sendgrid.net with SMTP id filter0632p1mdw1-19804-5AB8B38F-E
        2018-03-26 08:47:11.608707041 +0000 UTC
Received: from smtp.github.com (out-5.smtp.github.com [192.30.252.196])
	by ismtpd0010p1iad1.sendgrid.net (SG) with ESMTP id dTKsvckYTC602dz1j8FnHA
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:11.616 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:11 +0000 (UTC)
