### ISSUE TITLE
Update Engineering Guidelines

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#86]
* API snippets in design proposals first (as fast as possible), should be checked by reviewer
* Javadoc on interfaces and Swagger API documentation is mandatory. Has to be checked by a PR reviewer
* Add to PR review process that it can be synchronous. Discuss WIP limits on PR review
* Acceptance criterias should be part of every issue (still to clarify: how can this be more normative ?) 
* PR should be small (diff smaller than … lines, or other metric)

**Comment by zregvart** [comment]
I had Swagger snippet in syndesisio/syndesis-project#72 and later I removed it without anyone noticing, do we still feel the Swagger documentation is needed/helps?

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (178/150 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:8482)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nmk-0013eF-V5
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:23 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=fN6gQwAFueVERU/syya7xew7F74=; b=ODbKcpFdVXlmbuad
	/G5NSzJYj1iIwwnWgYb3Ou2h4V/NJv/ou7/tGUMplEtxeurUVII0WA+2KJ/fUKpE
	oGXeOo3vSFBdHrbu340Teopx4oLTxaO/DWcY707S21Sif2AXtJIcjzOmjP2Q1WOM
	eYWk018Mc1Tgl6LdOopZyKGm1Vk=
Received: by filter0606p1mdw1.sendgrid.net with SMTP id filter0606p1mdw1-15836-5AB8B38F-1B
        2018-03-26 08:47:11.825886735 +0000 UTC
Received: from smtp.github.com (out-1.smtp.github.com [192.30.252.192])
	by ismtpd0011p1iad2.sendgrid.net (SG) with ESMTP id Q5_td3eTT1SwnDqwydF7FQ
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:11.656 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:11 +0000 (UTC)
