### ISSUE TITLE
Update / Add README for best build+deployment experience

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-project#88]
Each individual repo should have some instructions how a development workflow including builds+deployments could look like.

Ideally based on the scripts in https://github.com/syndesisio/syndesis-project/tree/master/tools/minishift-build

**Comment by rhuss** [comment]
As this has been raised again in Sprint #18 retrospective, we should tackle this:

* Main focus: Quick turnaround times
* Evaluate hot deployment into the Minishift installation (e.g. mvn fabric8:watch)
* For code-compile-try cycle don’t use tests (-Pflash for the Java projects)
* Provide some quickstarts / tutorials for how a development process could look like (currently, everybody does it differently)

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (163/150 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:20901)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-18a6-hiram=hiramchirino.com@sgmail.github.com>)
	id 1f0Nmf-0013YZ-7A
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:17 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=YiKE1e7gK08oIwl6F6XMtEp3XqI=; b=KjrbhdRkfIdF3Qhi
	Dm6px+uLFMZXsDDRP2Iiwk4M7VtLz8wuGuvMfQSeuYdBr+7ZoZjvoWOuh1yFqjc8
	NdvWPH5cRBoIkqDF9ZmaX6wtAeXHZJCGT9YSoz46DPQmw/xO1xKs9ESOBxxpQ1FX
	QbY1uuhqfZb2LBS9pkofmZrOeow=
Received: by filter0808p1mdw1.sendgrid.net with SMTP id filter0808p1mdw1-24393-5AB8B388-6
        2018-03-26 08:47:04.226719058 +0000 UTC
Received: from smtp.github.com (out-5.smtp.github.com [192.30.252.196])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id nPyoSk9OSU2_S35LiHlvNQ
	for <hiram@hiramchirino.com>; Mon, 26 Mar 2018 08:47:04.257 +0000 (UTC)
Date: Mon, 26 Mar 2018 08:47:04 +0000 (UTC)
