### ISSUE TITLE
Updating an integration should trigger a redeployment of the integration deployment

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-project#9]
Right now once an integration is deployed, making update to it via the UI does not make it pick up the updates.

**Comment by rhuss** [comment]
Is this connected to #10 ? I mean we should discuss in general how a _redeployment_ should work. Changing an integration property alone should not update an integration automatically. There should be a dedicated "Redeploy" or "Update" button which then triggers the (costly) redeployment.

@kcbabo I think we need a user story for this 'update an integration' case.
