### ISSUE TITLE
Data mapper - cannot map date fields Twitter -> Salesforce

### ISSUE THREAD

**Issue by nichmoore** [syndesisio/syndesis-project#93]
1. On the Twitter to Salesforce scenario, the date fields cannot be mapped because they are different data types. One is a huge group field, and the other is a standard date format. 
 
2. If you try to map the date fields, an error message is displayed which says 'Conversion between source and target types is supported.' It appears in red and I assume it should read '... is NOT supported'.  It's not helpful.

**Comment by gashcrumb** [comment]
@igarashitm FYI

**Comment by igarashitm** [comment]
Found an existing issue reporting same behavior. duplicate?
syndesisio/syndesis-ui#677

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (180/150 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-4.smtp.github.com ([192.30.252.195]:58848)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nml-0013eg-AL
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:23 -0600
Date: Mon, 26 Mar 2018 01:47:12 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054032;
	bh=Wp6JP1FuaKTaXuNa0Acmg8D7/dLqM9IDKewRr5A0FoI=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=XBzNxs8mGYKfbV/U9G9JnTxWc84NJ4OQmAipQ9boNrH71CxL1mbubLq+g5K/A8st+
	 4UFEK8uNEJzocLBxECQSTpUYEz4DTICgb02Spt1GV56ULndyW5CuaddszYSd1Z65mb
	 uNxt42qxjNAoOjce58hlYvvWAS2gzCLuq27AMYug=
