### ISSUE TITLE
Specify form control order for action configuration

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-project#98]
Follow on from a discussion in https://github.com/syndesisio/syndesis-ui/issues/970

Currently the form control order is non-deterministic as it's stored as a hashmap.  We should consider ways to address this so our form controls are laid out consistently.

The approach the hawtio-forms implementation used was a separate array that specified the control order, this way the order of controls could be fairly loosely specified.

@rhuss FYI

**Comment by zregvart** [comment]
linking to http://forms.hawt.io/forms2/simple_form?main-tab=hawtio-forms2-tests-form2&sub-tab=hawtio-forms2-tests-form2-simple_form

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (186/150 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-4.smtp.github.com ([192.30.252.195]:59174)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nmm-0013ej-RI
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:25 -0600
Date: Mon, 26 Mar 2018 01:47:12 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054032;
	bh=nQ9FY7rs1pCtjyirkQja6sN9OVJFOWHHt+yeHKfEYpU=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=OnLxxMhI3dqnyOUBIvPTgnQggOcT6n6D09anCY7FPgzjvUw6rrk2oTQdVS/EwY9VL
	 DnkKhGbl34wU/Bmp0MEj70KCsYSiv/JhZ/x/PzeE94J9Q0uVbU9XihcqX7Fx+ybQ2u
	 7zIDqqwdj3BOGNnMeGFDYGxc2mAoGMiuDQijLJEU=
